name: dart_cli_playground
description: A sample command-line application.
# version: 1.0.0
# author: Jakub Jodełka <jakub@jodelka.me>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.2
  cli_util: ^0.1.3+2
  console: ^3.1.0
  io: ^0.3.3
  path: ^1.6.4
  http: ^0.12.0+2
  sprintf: ^4.0.2
  data_classes: ^2.0.2
  mustache: ^1.1.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.1
  data_classes_generator: 2.0.2
